trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet restore
  displayName: 'restaurando pacotes'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'realizando build - ambiente:$(buildConfiguration)'

- script: dotnet test
  displayName: 'executando testes'
