trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet restore
  displayName: 'restaurando pacotes'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'realizando build - ambiente:$(buildConfiguration)'

- script: dotnet test
  displayName: 'executando testes'    

- task: PublishBuildArtifacts@1    
  displayName: 'publicando artefato: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
 
- task: CopyFiles@2
  displayName: 'copiando arquivos'
  inputs:
    targetFolder: '$(Build.ArtifactStagingDirectory)'

