trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet restore
  displayName: 'restaurando pacotes'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'realizando build - ambiente:$(buildConfiguration)'

- script: dotnet test
  displayName: 'executando testes'    

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

# this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your build.
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'biblioteca-app'
    
# - task: CopyFiles@2
#   displayName: 'copiando arquivos'
#   inputs:
#     targetFolder: '$(Build.ArtifactStagingDirectory)'

